project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /lib/l10n/app_en.arb
    translation: /lib/l10n/app_%locale_with_underscore%.arb
    update_option: update_as_unapproved
  
  - source: /fastlane/metadata/android/en-US/*.txt
    translation: /fastlane/metadata/android/%locale%/%original_file_name%
    update_option: update_as_unapproved
    ignore:
      - /**/keywords.txt
      - /**/video.txt