name: quitter
description: "Quit addictions with Free and Open Source software"
publish_to: 'none'
version: 1.0.2+3
environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  dynamic_color: ^1.8.1
  flutter_svg: ^2.0.13
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 # Add this line
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/icon/
msix_config:
  msix_version: null..2.
