#!/usr/bin/env bash
# Generates lib/material_icons.dart: a map of every base (filled) Material icon
# in the current Flutter SDK, keyed by its Dart identifier name.
#
# Variant styles (_outlined / _rounded / _sharp / _two_tone) are excluded so the
# picker shows one entry per icon. Values reference the const Icons.* fields, so
# the build can still tree-shake (it keeps exactly the referenced glyphs).
#
# Regenerate after a Flutter SDK upgrade:
#   bash tool/gen_material_icons.sh
set -euo pipefail

flutter_root="$(dirname "$(dirname "$(readlink -f "$(command -v flutter)")")")"
src="$flutter_root/packages/flutter/lib/src/material/icons.dart"
out="$(dirname "$0")/../lib/material_icons.dart"

if [[ ! -f "$src" ]]; then
  echo "Could not find Material icons source at: $src" >&2
  exit 1
fi

{
  echo "// GENERATED by tool/gen_material_icons.sh — do not edit by hand."
  echo "// Regenerate after a Flutter SDK upgrade: bash tool/gen_material_icons.sh"
  echo
  echo "import 'package:flutter/material.dart';"
  echo
  echo "/// Every base (filled) Material icon, keyed by its Dart identifier name."
  echo "const Map<String, IconData> allMaterialIcons = {"
  grep -oE 'static const IconData [a-z0-9_]+ = IconData\(' "$src" \
    | sed -E 's/static const IconData ([a-z0-9_]+) = IconData\(/\1/' \
    | grep -vE '_(outlined|rounded|sharp|two_tone)$' \
    | sort -u \
    | while read -r name; do
        printf "  '%s': Icons.%s,\n" "$name" "$name"
      done
  echo "};"
} >"$out"

count=$(($(grep -cE "  '" "$out")))
echo "Wrote $out ($count icons)"
